services:
  postgres:
    image: postgres:14
    container_name: pact-postgres
    restart: always
    mem_limit: 256m
    cpus: 0.25
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: pact
      POSTGRES_DB: pact
    volumes:
      - pact-postgres-data:/var/lib/postgresql/data

  pact-broker:
    image: pactfoundation/pact-broker:latest
    container_name: pact-broker
    restart: always
    mem_limit: 256m
    cpus: 0.25
    depends_on:
      - postgres
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_ADAPTER: postgres
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_PORT: 5432
      PACT_BROKER_DATABASE_NAME: pact
      PACT_BROKER_DATABASE_USERNAME: pact
      PACT_BROKER_DATABASE_PASSWORD: pact

      
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_PUBLIC_HEARTBEAT: "true"
      PACT_BROKER_BASE_URL: http://localhost:9292

volumes:
  pact-postgres-data:
